import type { AiDegradedReason } from "./provider";

/**
 * What the AI panel prints after "Generated by". A heuristic result is
 * labelled by *why* the model was not used: a fresh install with no key is
 * not an outage, and an outage should not read like a fresh install.
 * Type-only import above, so this stays importable from the client.
 */
const DEGRADED_LABELS: Record<AiDegradedReason, string> = {
  not_configured: "rule-based mode (no AI key configured)",
  rate_limited: "rule-based fallback (AI provider rate-limited)",
  error: "rule-based fallback (AI provider error)",
  malformed: "rule-based fallback (AI reply was not usable)",
};

export function providerLabel(result: { provider: string; degraded?: AiDegradedReason }): string {
  if (result.provider !== "heuristic") return result.provider;
  return result.degraded ? DEGRADED_LABELS[result.degraded] : "rule-based fallback";
}
