import { describe, expect, it } from "vitest";
import { providerLabel } from "./label";

// The panel footer reads "Generated by <label>". Before the reason existed
// it said "AI provider unavailable" for every heuristic result, including a
// fresh install with no key at all, which is not unavailability.
describe("providerLabel", () => {
  it("names the model that answered", () => {
    expect(providerLabel({ provider: "gemini/gemini-3.6-flash" })).toBe(
      "gemini/gemini-3.6-flash",
    );
  });

  it("says no key is configured, not that a provider is down", () => {
    expect(providerLabel({ provider: "heuristic", degraded: "not_configured" })).toBe(
      "rule-based mode (no API key configured)",
    );
  });

  it.each([
    ["rate_limited", "rule-based fallback (AI provider rate-limited)"],
    ["error", "rule-based fallback (AI provider error)"],
    ["malformed", "rule-based fallback (AI reply was not usable)"],
  ] as const)("names the failure for %s", (degraded, label) => {
    expect(providerLabel({ provider: "heuristic", degraded })).toBe(label);
  });

  it("still labels a heuristic result that carries no reason", () => {
    expect(providerLabel({ provider: "heuristic" })).toBe("rule-based fallback");
  });
});
